### ISSUE TITLE
Update the readme.

### ISSUE THREAD

**Issue by awasum** [skylabaseInc/fineract-web-app#3]
Put info to help people set up dev env and production builds that can be run on apache web server, Nginx and Tomcat.

**Comment by awasum** [comment]
Have u seen this @kengneruphine , @pembemiriam ??

**Comment by awasum** [comment]
Testing

**Comment by awasum** [comment]
testing

**Comment by awasum** [comment]
Test again

**Comment by awasum** [comment]
test gain

**Comment by awasum** [comment]
What of this work?? No one is attending to them eehh?

**Comment by awasum** [comment]
@pembemiriam ..Do this work today..Please...WTF are you doing not paying attention to this...DO not do anything on this project until u have done this work.

**Comment by awasum** [comment]
Is this done @pembemiriam ??

**Comment by pembemiriam** [comment]
done

**Comment by awasum** [comment]
Next time..when u completed an issues...just comment on it..so that i know to test and close the issue.
